name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image to Azure Container Registry (ACR)
        run: |
          docker build -t ${{ secrets.ACR_URL }}/alumnibackend:latest .
          docker push ${{ secrets.ACR_URL }}/alumnibackend:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: alumni-web
          images: ${{ secrets.ACR_URL }}/alumnibackend:latest