name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build the Java application
        run: chmod +x ./gradlew && ./gradlew build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_URL }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image to Azure Container Registry (ACR)
        run: |
          docker build -t ${{ secrets.ACR_URL }}/alumnibackend:latest .
          docker push ${{ secrets.ACR_URL }}/alumnibackend:latest

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli
          az --version
          
      - name: Explicit Azure CLI Login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: alumni-web
          images: ${{ secrets.ACR_URL }}/alumnibackend:latest